#!/bin/bash

SERVER_PID=""

function finish() {
    if [[ "$SERVER_PID" != "" ]]
    then
        if ! [[ "$SERVER_PID" =~ ^[0-9]+$ ]]
        then
            echo "ERROR: Invalid pid $SERVER_PID!"
            exit 1
        fi
        kill "$SERVER_PID" &>/dev/null
        SERVER_PID=""
    fi
}
function run_server() {

    finish
    make
    cd docs
    python3 -m http.server 8080 &>/dev/null & 
    SERVER_PID=$!
    cd ..
    echo "Server started!"
    echo "Visit http://localhost:8080 in your browser. Make edits to the files in src/ and it will automatically reload"
    echo "Press ctrl+c to stop"

}
function get_hash(){
    echo $(find src -type f -name '*.html' -exec cat '{}' \; | md5sum | awk '{print $1}')
}

trap finish EXIT
current_hash="$(get_hash)"
run_server
while true
do
    sleep 1
    new_hash="$(get_hash)"
    if [[ "$new_hash" != "$current_hash" ]]
    then
        echo "Change detected! Restarting..."
        run_server
        current_hash=$new_hash
    fi


done
